# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PCbotUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1343, 701)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BG_1 = QtWidgets.QLabel(self.centralwidget)
        self.BG_1.setGeometry(QtCore.QRect(-70, 0, 1411, 751))
        self.BG_1.setText("")
        self.BG_1.setPixmap(QtGui.QPixmap("../../../Downloads/white.jpg"))
        self.BG_1.setScaledContents(True)
        self.BG_1.setObjectName("BG_1")
        
        self.GIF_1 = QtWidgets.QLabel(self.centralwidget)
        self.GIF_1.setGeometry(QtCore.QRect(-80, 10, 581, 431))
        self.GIF_1.setText("")
        self.GIF_1.setPixmap(QtGui.QPixmap("../../../Downloads/chatbot-unscreen.gif"))
        self.GIF_1.setScaledContents(True)
        self.GIF_1.setObjectName("GIF_1")
        
        self.pushButton_what = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_what.setGeometry(QtCore.QRect(280, 570, 141, 61))
        self.pushButton_what.setStyleSheet("background-color:rgb(85, 255, 255)")
        self.pushButton_what.setObjectName("pushButton_what")
        
        self.pushButton_you = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_you.setGeometry(QtCore.QRect(500, 570, 141, 61))
        self.pushButton_you.setStyleSheet("background-color:rgb(85, 255, 255)")
        self.pushButton_you.setObjectName("pushButton_you")
        
        self.pushButton_chrome = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_chrome.setGeometry(QtCore.QRect(50, 570, 141, 61))
        self.pushButton_chrome.setStyleSheet("background-color:rgb(85, 255, 255)")
        self.pushButton_chrome.setObjectName("pushButton_chrome")
        
        self.Chat_con = QtWidgets.QLabel(self.centralwidget)
        self.Chat_con.setGeometry(QtCore.QRect(690, 0, 651, 491))
        self.Chat_con.setStyleSheet("background-color:rgb(58, 58, 58)")
        self.Chat_con.setText("")
        self.Chat_con.setObjectName("Chat_con")
        
        self.Chat_con_2 = QtWidgets.QLabel(self.centralwidget)
        self.Chat_con_2.setGeometry(QtCore.QRect(-10, 0, 701, 491))
        self.Chat_con_2.setStyleSheet("background-color:rgb(58, 58, 58)")
        self.Chat_con_2.setText("")
        self.Chat_con_2.setObjectName("Chat_con_2")
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 571, 471))
        self.label.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.label.setText("")
        self.label.setObjectName("label")
        
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(790, 570, 141, 61))
        self.pushButton_start.setStyleSheet("background-color:rgb(0, 255, 0)")
        self.pushButton_start.setObjectName("pushButton_start")
        
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(1100, 570, 141, 61))
        self.pushButton_exit.setStyleSheet("background-color:rgb(255, 0, 0)")
        self.pushButton_exit.setObjectName("pushButton_exit")
        
        self.Chat_con_3 = QtWidgets.QLabel(self.centralwidget)
        self.Chat_con_3.setGeometry(QtCore.QRect(0, 490, 1341, 521))
        self.Chat_con_3.setStyleSheet("background-color:rgb(58, 58, 58)")
        self.Chat_con_3.setText("")
        self.Chat_con_3.setObjectName("Chat_con_3")
        
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 530, 1311, 131))
        self.label_2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        
        self.Temp_show = QtWidgets.QTextBrowser(self.centralwidget)
        self.Temp_show.setGeometry(QtCore.QRect(80, 490, 241, 31))
        self.Temp_show.setObjectName("Temp_show")
        self.Time_show = QtWidgets.QTextBrowser(self.centralwidget)
        self.Time_show.setGeometry(QtCore.QRect(1040, 490, 241, 31))
        self.Time_show.setObjectName("Time_show")
        
        self.chat_show = QtWidgets.QTextBrowser(self.centralwidget)
        self.chat_show.setGeometry(QtCore.QRect(790, 10, 541, 471))
        self.chat_show.setObjectName("chat_show")
        self.Date_show = QtWidgets.QTextBrowser(self.centralwidget)
        self.Date_show.setGeometry(QtCore.QRect(740, 490, 241, 31))
        self.Date_show.setObjectName("Date_show")
        self.Day_show = QtWidgets.QTextBrowser(self.centralwidget)
        self.Day_show.setGeometry(QtCore.QRect(390, 490, 241, 31))
        self.Day_show.setObjectName("Day_show")
        
        self.Day_show_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.Day_show_2.setGeometry(QtCore.QRect(590, 10, 191, 121))
        self.Day_show_2.setObjectName("Day_show_2")
        
        self.Day_show_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.Day_show_3.setGeometry(QtCore.QRect(590, 360, 191, 121))
        self.Day_show_3.setObjectName("Day_show_3")
        
        self.loading = QtWidgets.QLabel(self.centralwidget)
        self.loading.setGeometry(QtCore.QRect(580, 130, 211, 231))
        self.loading.setText("")
        self.loading.setPixmap(QtGui.QPixmap("../../../Downloads/load.gif"))
        self.loading.setScaledContents(True)
        self.loading.setObjectName("loading")
        
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(789, 9, 541, 471))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 0, 541, 471))
        self.plainTextEdit.setObjectName("plainTextEdit")
        
        self.speaking = QtWidgets.QLabel(self.centralwidget)
        self.speaking.setGeometry(QtCore.QRect(580, 130, 201, 231))
        self.speaking.setText("")
        self.speaking.setPixmap(QtGui.QPixmap("../../../Downloads/speak.gif"))
        self.speaking.setScaledContents(True)
        self.speaking.setObjectName("speaking")
        
        self.Listening = QtWidgets.QLabel(self.centralwidget)
        self.Listening.setGeometry(QtCore.QRect(580, 130, 201, 231))
        self.Listening.setText("")
        self.Listening.setPixmap(QtGui.QPixmap("../../../Downloads/listening.gif"))
        self.Listening.setScaledContents(True)
        self.Listening.setObjectName("Listening")
        
        self.BG_1.raise_()
        self.Chat_con_3.raise_()
        self.Chat_con.raise_()
        self.Chat_con_2.raise_()
        self.label.raise_()
        self.GIF_1.raise_()
        self.label_2.raise_()
        self.pushButton_chrome.raise_()
        self.pushButton_what.raise_()
        self.pushButton_you.raise_()
        self.pushButton_start.raise_()
        self.pushButton_exit.raise_()
        self.Temp_show.raise_()
        self.Time_show.raise_()
        self.chat_show.raise_()
        self.Date_show.raise_()
        self.Day_show.raise_()
        self.Day_show_2.raise_()
        self.Day_show_3.raise_()
        self.loading.raise_()
        self.frame.raise_()
        self.speaking.raise_()
        self.Listening.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_what.setText(_translate("MainWindow", "WhatsApp"))
        self.pushButton_you.setText(_translate("MainWindow", "YouTube"))
        self.pushButton_chrome.setText(_translate("MainWindow", "Chrome"))
        self.pushButton_start.setText(_translate("MainWindow", "START"))
        self.pushButton_exit.setText(_translate("MainWindow", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
